# Generated by Django 4.0.4 on 2022-10-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Component Name')),
                ('amount', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50, verbose_name='Component Color')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('shortdesc', models.CharField(max_length=50, verbose_name='Short Desc')),
                ('longdesc', models.TextField(verbose_name='Long Desc')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Base Price')),
                ('mainimg', models.ImageField(upload_to='images/', verbose_name='Main Image')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date Updated')),
                ('isactive', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
                ('components', models.ManyToManyField(to='store.component')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-updated'],
            },
        ),
    ]
