# Generated by Django 4.0.4 on 2022-10-26 16:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_category_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mainimg',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[500, 300], upload_to='images/%Y/%m/%d/'),
        ),
    ]
