# Generated by Django 4.0.4 on 2022-11-08 16:21

from django.db import migrations
import django_resized.forms
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_mainimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mainimg',
            field=django_resized.forms.ResizedImageField(crop=None, default='static/images/default.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[800, 600], upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=model_utils.fields.StatusField(choices=[('ar15', 'ar15'), ('ar308', 'ar308'), ('tac9', 'tac9'), ('tn9p', 'tn9p'), ('80%', '80%'), ('parts', 'parts')], db_index=True, default='ar15', max_length=50, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimg',
            field=django_resized.forms.ResizedImageField(crop=None, default='static/images/default.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[800, 600], upload_to='static/images/'),
        ),
    ]
